name: Pull and Run Docker Image
 
on:

  pull_request:

    branches: 

      - main
 
jobs:

  pull-and-run:

    runs-on: ubuntu-latest

    steps:

    - name: Log in to Docker Hub

      uses: docker/login-action@v1

      with:

        username: ${{ secrets.DOCKER_USERNAME }}

        password: ${{ secrets.DOCKER_PASSWORD }}
 
    - name: Pull Docker image

      run: docker pull rajaj0110/rajajccid
 
    - name: Run Docker image

      run: docker run --name test_container yourusername/yourimagename:latest
 
    - name: Check test score

      run: |

        docker logs test_container > output.log

        SCORE=$(grep -oP 'Score: \K[0-9.]+' output.log)

        if (( $(echo "$SCORE > 0.50" | bc -l) )); then

          echo "Test Passed"

        else

          echo "Test Failed"

          exit 1

        fi
